# This is a basic workflow to help you get started with Actions

name: Build and Deploy the Unity Project to GitHub Page

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildWebGL:
    name: Build For WebGL
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Restore Library Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-build-WebGL
          restore-keys: 
            Library-
            Library-build-
            
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          
      - uses: actions/upload-artifact@v2
        with:
          name: build-WebGL
          path: build/WebGL
        
  deployPages:
    needs: buildWebGL
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      pages: write # to deploy to Pages
      contents: write
      id-token: write # to verify the deployment orginate from an appropriate source
      deployments: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}     
    steps:
      - name: Checkout Code 
        uses: actions/checkout@v2
        
      - uses: actions/download-artifact@v2
        with:
          name: build-WebGL
          path: build
        
      - name: Deploy to GitHub Page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
